#!/bin/bash
# Helper script to check teams in Xcode

echo "=========================================="
echo "  Finding Team ID for admin@sphereemr.com"
echo "=========================================="
echo ""

echo "📋 Instructions:"
echo ""
echo "1. Xcode should be open now"
echo "2. Go to: Xcode > Settings (or press Cmd+,)"
echo "3. Click the 'Accounts' tab"
echo "4. Find 'admin@sphereemr.com' in the list"
echo "5. Click on it"
echo "6. Look for 'Team ID' on the right side"
echo ""
echo "OR"
echo ""
echo "1. In Xcode, open the project (Runner.xcworkspace)"
echo "2. Click the blue 'Runner' project icon (top of left sidebar)"
echo "3. Select 'Runner' under TARGETS"
echo "4. Click 'Signing & Capabilities' tab"
echo "5. Click the 'Team' dropdown"
echo "6. Find the team for admin@sphereemr.com"
echo "7. The Team ID is shown in parentheses"
echo ""
echo "=========================================="
echo ""
echo "Once you find it, the Team ID will look like:"
echo "  - 44GY3MRW88"
echo "  - RZW6S4A75D"
echo "  - ABC123XYZ"
echo ""
echo "Then run: ./update_team.sh <TEAM_ID>"
echo ""

